'use client'
import {useState} from 'react'
import {CalendarDays, Check, ChevronLeft, ChevronRight, LogOut, Plus, Sparkles} from 'lucide-react'
import {mock} from '@/lib/api'
type Task=typeof mock.tasks[number]
function Logo(){return <div className="brand"><span className="brand-mark"><Sparkles size={16}/></span> studyflow</div>}
function Login({done}:{done:()=>void}){const [signup,setSignup]=useState(false);return <main className="login-wrap"><section className="login"><Logo/><h1>{signup?'Create your account':'Welcome back'}</h1><p>{signup?'Let’s make your semester feel a little lighter.':'Your calm corner for getting things done.'}</p><div className="toggle"><button className={!signup?'selected':''} onClick={()=>setSignup(false)}>Log in</button><button className={signup?'selected':''} onClick={()=>setSignup(true)}>Sign up</button></div>{signup&&<div className="field"><label>First name</label><input placeholder="Alex"/></div>}<div className="field"><label>Email address</label><input placeholder="you@university.edu"/></div><div className="field"><label>Password</label><input type="password" placeholder="••••••••"/></div><button className="primary" onClick={done}>{signup?'Create account':'Log in'} →</button></section></main>}
function Nav({page,setPage,logout}:{page:string;setPage:(x:string)=>void;logout:()=>void}){return <nav className="nav"><Logo/><div className="nav-links"><button className={page==='dashboard'?'active':''} onClick={()=>setPage('dashboard')}>Dashboard</button><button className={page==='calendar'?'active':''} onClick={()=>setPage('calendar')}>Calendar</button></div><div className="profile"><div className="avatar">AS</div><span>Alex Smith</span><button className="icon-btn" onClick={logout}><LogOut size={16}/></button></div></nav>}
function Dashboard(){const [tasks,setTasks]=useState<Task[]>(mock.tasks);const toggle=(id:string)=>setTasks(x=>x.map(t=>t.id===id?{...t,completed:!t.completed}:t));return <div className="content"><div className="hero"><div><div className="eyebrow">Tuesday, September 24</div><h1>Good morning, Alex</h1><p>Small steps make a big difference. You’ve got this.</p></div><div className="date-pill">☀️ 72° · Campus</div></div><div className="grid"><section className="card"><div className="card-head"><h2>Today&apos;s plan</h2><span className="subtle">3 items</span></div>{tasks.slice(0,3).map(t=><div className="task" key={t.id}><input className="check" type="checkbox" checked={t.completed} onChange={()=>toggle(t.id)}/><span className={`task-title ${t.completed?'done':''}`}>{t.title}</span><span className="tag" style={{background:t.color}}>{t.type}</span></div>)}</section><section className="card"><div className="card-head"><h2>Upcoming deadlines</h2><span className="subtle">Next 5</span></div>{tasks.slice(3).map(t=><div className="deadline" key={t.id}><i className="deadline-dot" style={{background:t.color}}/><div className="deadline-info"><strong>{t.title}</strong><span>{t.subject} · {t.type}</span></div><span className="days">{t.due}</span></div>)}</section></div><section className="section card"><div className="card-head"><h2>Your subjects</h2><span className="subtle">Keep it colorful</span></div><div className="subjects">{mock.subjects.map(s=><button className="subject" style={{background:s.color}} key={s.id}>{s.name}</button>)}<button className="subject add"><Plus size={18}/></button></div></section><section className="section"><div className="stats"><div className="stat lav"><span>Pending tasks</span><strong>4</strong></div><div className="stat mint"><span>Completed this week</span><strong>18</strong></div><div className="stat peach"><span>Overdue</span><strong>2</strong></div><div className="stat yellow"><span>Upcoming exams</span><strong>3</strong></div></div></section><section className="section card"><div className="card-head"><h2>Tasks completed</h2><span className="subtle">This week</span></div><div className="chart">{[45,68,38,82,58,30,8].map((h,i)=><div className="bar" style={{height:`${h}%`}} key={i}><label>{['M','T','W','T','F','S','S'][i]}</label></div>)}</div></section></div>}
function Calendar(){const [month,setMonth]=useState(new Date(2024,8,1));const days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();const start=new Date(month.getFullYear(),month.getMonth(),1).getDay();const cells=Array.from({length:42},(_,i)=>i-start+1);return <div className="content"><div className="hero"><div><div className="eyebrow">Plan your month</div><h1>Calendar</h1><p>See everything coming up at a glance.</p></div><button className="date-pill" onClick={()=>setMonth(new Date(2024,8,1))}>Today</button></div><section className="calendar"><div className="cal-head"><h2>{month.toLocaleString('en-US',{month:'long',year:'numeric'})}</h2><div className="cal-actions"><button className="icon-btn" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}><ChevronLeft/></button><button className="icon-btn" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}><ChevronRight/></button></div></div><div className="week">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=><div key={x}>{x}</div>)}</div><div className="days-grid">{cells.map(n=><div className={`day ${n<1||n>days?'muted-day':''} ${n===24?'today':''}`} key={n}><span className="day-num">{n>0&&n<=days?n:''}</span>{n===24&&<span className="cal-chip" style={{background:'#c9b8f6'}}>Read chapter 4</span>}{n===25&&<span className="cal-chip" style={{background:'#f7d79b'}}>Group presentation</span>}</div>)}</div></section></div>}
export default function Home(){const [logged,setLogged]=useState(false);const [page,setPage]=useState('dashboard');if(!logged)return <Login done={()=>setLogged(true)}/>;return <div className="shell"><Nav page={page} setPage={setPage} logout={()=>setLogged(false)}/>{page==='dashboard'?<Dashboard/>:<Calendar/>}</div>}
